"""Initial migration

Revision ID: 47489e3ff58c
Revises: 
Create Date: 2026-01-18 16:27:38.112967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47489e3ff58c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('source_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created_at', 'prices', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_ticker_timestamp', 'prices', ['ticker', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('ix_prices_id'), 'prices', ['id'], unique=False)
    op.create_index(op.f('ix_prices_ticker'), 'prices', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prices_ticker'), table_name='prices')
    op.drop_index(op.f('ix_prices_id'), table_name='prices')
    op.drop_index('idx_ticker_timestamp', table_name='prices')
    op.drop_index('idx_created_at', table_name='prices')
    op.drop_table('prices')
    # ### end Alembic commands ###
